name: aether-prod

services:
  postgresql:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 2s
      retries: 300
    environment:
      POSTGRES_DB: impress
      POSTGRES_USER: impress
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_prod_password_change_this}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:5
    volumes:
      - redis_data:/data
    restart: unless-stopped

  app:
    build:
      context: .
      target: backend-production
      args:
        DOCKER_USER: 1000
    image: aether:backend-production
    environment:
      - DJANGO_CONFIGURATION=Production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-change_this_secret_key_in_production}
      - DB_HOST=postgresql
      - DB_NAME=impress
      - DB_USER=impress
      - DB_PASSWORD=${POSTGRES_PASSWORD:-secure_prod_password_change_this}
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/1
      - REDIS_SESSION_URL=redis://redis:6379/2
      - ALLOWED_HOSTS=aethers.ru,aetherhelp.store,45.146.166.126,localhost
      - CSRF_TRUSTED_ORIGINS=https://aethers.ru,https://aetherhelp.store,http://45.146.166.126:8071
      - CORS_ALLOW_ALL_ORIGINS=false
      - CORS_ALLOWED_ORIGINS=https://aethers.ru,https://aetherhelp.store
      - SECURE_SSL_REDIRECT=true
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - SESSION_COOKIE_SECURE=true
      - CSRF_COOKIE_SECURE=true
      - SESSION_COOKIE_DOMAIN=.aethers.ru
      - LANGUAGE_COOKIE_NAME=aether_language
    volumes:
      - static_data:/data/static
      - media_data:/data/media
    depends_on:
      postgresql:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: ./src/frontend/Dockerfile
      target: impress-production
      args:
        API_ORIGIN: "https://aethers.ru"
        NEXT_PUBLIC_API_ORIGIN: "https://aethers.ru"
        PUBLISH_AS_MIT: "false"
        SW_DEACTIVATED: "false"
    image: aether:frontend-production
    environment:
      - NEXT_PUBLIC_API_ORIGIN=https://aethers.ru
      - API_ORIGIN=https://aethers.ru
      - PORT=3000
    restart: unless-stopped

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/data/static:ro
      - media_data:/data/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
      - frontend
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    volumes:
      - ./docker/auth/realm.json:/opt/keycloak/data/import/realm.json
      - ./docker/keycloak-themes/aether:/opt/keycloak/themes/aether
    command:
      - start
      - --features=preview
      - --import-realm
      - --proxy=edge
      - --hostname-url=https://aethers.ru
      - --hostname-admin-url=https://aethers.ru/auth/admin/
      - --hostname-strict=false
      - --health-enabled=true
      - --metrics-enabled=true
    healthcheck:
      test: ["CMD", "curl", "--head", "-fsS", "http://localhost:8080/health/ready"]
      interval: 1s
      timeout: 2s
      retries: 300
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin_change_this}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/impress
      KC_DB_USERNAME: impress
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-secure_prod_password_change_this}
      KC_HOSTNAME: aethers.ru
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: false
      KC_PROXY: edge
    depends_on:
      - postgresql
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_data:
  media_data: 